better_user_settings:
  groups:
    garten:
      users:
        - home_assistant_user_id_1
        - home_assistant_user_id_2
    admins:
      users:
        - admin_user_id

  dashboards:
    /dashboard-garten:
      groups:
        - garten
        - admins
    /lovelace-tablet:
      groups:
        - admins

  sidebar_items:
    /map:
      groups:
        - garten
        - admins
    /logbook:
      groups:
        - admins

  options:
    hide_sidebar_items: true
    redirect_blocked_dashboards: true
    hide_admin_menu_for_non_admin: false
    debug: false
